app/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Task(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(200), nullable=False)

app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.models import db, Task

routes = Blueprint('routes', __name__, template_folder='templates')

@routes.route('/home')
def home():
  return '<h1>Taskly</h1>'

@routes.route('/login')
def login():
  return render_template('login.j2')

@routes.route('/register')
def register():
  return render_template('register.j2')

@routes.route('/')
def toDoApp():
  tasks = Task.query.all()
  return render_template('layout.j2', tasks=tasks)


# Crud Routes

@routes.route('/add', methods=['POST'])
def add():
  name = request.form['name']
  new_task = Task(name=name)
  db.session.add(new_task)
  db.session.commit()
  return redirect(url_for('routes.toDoApp'))

@routes.route('/delete/<int:id>', methods=['GET', 'POST'])
def delete(id):
  task = Task.query.get(id)
  db.session.delete(task)
  db.session.commit()
  return redirect(url_for('routes.toDoApp'))

app/templates/base.j2
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title%} {% endblock%}</title> <!-- Block title -->
  <!-- CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css')}}">

  <!-- Fonts  -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"> 

  <!-- Custom css in different pages -->
  {% block css %}
  
  {% endblock %}
</head>
<body>
  <main role="main">
    {% block body%}

    {% endblock%}
  </main>
</body>
</html>

app/templates/layout.j2
{% extends "base.j2" %}

{% block title%} Taslky {% endblock  %}

{% block css %}
<link rel="stylesheet" href="{{url_for('static', filename='css/layout.css')}}">
{% endblock %}

{% block body %}
<h1>Taskly</h1>
<div class="input-div">
  <form class="task-form" action="{{ url_for('routes.add')}}" method="post">
    <input class="input-form" type="text" name="name" placeholder="Agregar Tarea" required>
    <button class="form-btn">Agregar</button>
  </form>
</div>
<div class="task-list">
  <ul>
    {% for task in tasks%}
      <li class="taks-li">
        {{task.name}}
        <a href="{{url_for('routes.delete', id=task.id)}}">🗑</a>
      </li>
    {% endfor %}
  </ul>
  
</div>
{% endblock  %}